apiVersion: v1
kind: Secret
metadata:
  name: perforce-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  P4PASSWD: {{ .Values.P4.password | b64enc }}
  P4USER: {{ .Values.P4.admin | b64enc }}