apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "perforce.fullname" . }}
  labels:
    {{- include "perforce.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "perforce.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "perforce.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "perforce.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: P4PASSWD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.existingSecret }}"
                  key: P4PASSWD
          ports:
            - name: perforce
              containerPort: 1666
              protocol: TCP
          volumeMounts:
            - name: data-dir
              mountPath: /data
            - name: ldap-file
              mountPath: /root/p4-ldap.txt
              subPath: p4-ldap.txt
            - name: ldap-groups
              mountPath: /root/p4-ldap-groups.txt
              subPath: p4-ldap-groups.txt
          livenessProbe:
            tcpSocket:
              port: 1666
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 1666
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        - name: ldap-file
          configMap:
            name: perforce-ldap
        - name: ldap-groups
          configMap:
            name: perforce-groups
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
